# Generated by Django 4.2.11 on 2024-08-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shipping_address',
            field=models.CharField(default='Not Set', max_length=500),
        ),
    ]
