# Generated by Django 5.1.4 on 2025-04-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='categroy',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
